### ISSUE TITLE
Add this to TTT lang list

### ISSUE THREAD

**Issue by Blueberryy** [Decicus/TTT-Scoreboard-Ranks-for-ULX#8]
I would like to translate these
https://github.com/Decicus/TTT-Scoreboard-Ranks-for-ULX/blob/ab12620dbdcce2045514a8abcbf02a8e725a7761/lua/autorun/server/sv_tttsbranks.lua#L11

**Comment by Decicus** [comment]
I don't really see the point of adding translation support for those values specifically, as they are generally meant to be changed by server administrators when they initially set up the addon (that's what the commands [`columnname`](https://github.com/Decicus/TTT-Scoreboard-Ranks-for-ULX/blob/master/lua/ulx/modules/sh/ttt_sb_ranks.lua#L279-L292) and [`defaultrank`](https://github.com/Decicus/TTT-Scoreboard-Ranks-for-ULX/blob/master/lua/ulx/modules/sh/ttt_sb_ranks.lua#L299-L308) are for).

The help texts and such might be a good idea to have translations for, but that's a lot more work. I've added it to the list I made in issue #7, but my interest for maintaining this addon hasn't really increased and it's unlikely that I'll ever get around to doing the work that mentioned there.

Anyways, I'm closing this issue for now (since translation support has been mentioned in #7). Thanks for the suggestion :)
